// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BackEnd.Client.Models
{
    using System.Linq;

    public partial class ClientDTO
    {
        /// <summary>
        /// Initializes a new instance of the ClientDTO class.
        /// </summary>
        public ClientDTO() { }

        /// <summary>
        /// Initializes a new instance of the ClientDTO class.
        /// </summary>
        public ClientDTO(string id = default(string), string name = default(string), string email = default(string), string role = default(string))
        {
            Id = id;
            Name = name;
            Email = email;
            Role = role;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Role")]
        public string Role { get; set; }

    }
}
