// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BackEnd.Client.Models
{
    using System.Linq;

    public partial class PolicyDTO
    {
        /// <summary>
        /// Initializes a new instance of the PolicyDTO class.
        /// </summary>
        public PolicyDTO() { }

        /// <summary>
        /// Initializes a new instance of the PolicyDTO class.
        /// </summary>
        public PolicyDTO(string id = default(string), double? amountInsured = default(double?), string email = default(string), System.DateTime? inceptionDate = default(System.DateTime?), bool? installmentPayment = default(bool?), string clientId = default(string))
        {
            Id = id;
            AmountInsured = amountInsured;
            Email = email;
            InceptionDate = inceptionDate;
            InstallmentPayment = installmentPayment;
            ClientId = clientId;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "AmountInsured")]
        public double? AmountInsured { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "InceptionDate")]
        public System.DateTime? InceptionDate { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "InstallmentPayment")]
        public bool? InstallmentPayment { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

    }
}
